import datastructures
stack = datastructures.Stack.Stack()
queue = datastructures.Queue.Queue()
stack.push(12)
stack.push(11)
stack.push(22)
stack.push(102)
stack.push(112)
stack.display()
print(stack.pop())
print(stack.pop())
print(stack.top())
stack.display()
queue.add(12)
queue.add(121)
queue.add(112)
queue.add(120)
queue.add(22)
queue.display()
print(queue.remove())
print(queue.remove())
print(queue.front())
print(queue.rear())
queue.display()
